### ISSUE TITLE
Please add install instructions to README.md

### ISSUE THREAD

**Issue by nmarley** [yaegashi/ansible-role-blockinfile#11]
I want to use this module, but don't know how to install this at all.

I get an (expected) error when using homebrew'd ansible, b/c I didn't install this yet (and don't know how).

```
ERROR: blockinfile is not a legal parameter in an Ansible task or handler
```

**Comment by pgdagenais** [comment]
Install the module with ansible galaxy with this command :

`ansible-galaxy install yaegashi.blockinfile`

and then add something like this in your playbook :

``` YAML
roles:
  - yaegashi.blockinfile
  - apache
  - munin
```

and then something like this in your tasks:

``` YAML
- name: add server as client
  blockinfile: 
    dest: /etc/munin/munin.conf
    state: present
    marker: "#{mark} ANSIBLE MANAGED BLOCK"
    block: |
      [{{ ansible_hostname }}] 
        address {{ ['ansible_eth1']['ipv4']['address'] }}
        use_node_name yes 
```
