### ISSUE TITLE
Content from template files

### ISSUE THREAD

**Issue by shopblocks** [yaegashi/ansible-role-blockinfile#14]
Is it possible to get the content from a j2 template file?

**Comment by vartagg** [comment]
+1

**Comment by alimac** [comment]
Yes, it is possible to get content from a file or template, using `lookup`. For example:

```
- name: update ssh config
  blockinfile:
    backup: yes
    create: yes
    dest: ~/.ssh/config
    block: |
      {{ lookup('file', 'templates/ssh_config.j2') }}
  tags: ssh
```
