### ISSUE TITLE
Spacing in blocks does not work as expected

### ISSUE THREAD

**Issue by dobber** [yaegashi/ansible-role-blockinfile#8]
- name: Add logstash-forwarder to datadog process monitoring
  blockinfile:
    dest: /etc/dd-agent/conf.d/process.yaml
    block: |
      - name: logstash-forwarder
        search_string: ['logstash-forwarder']
        exact_match: false
        thresholds:
          # critical if no server.py is running
          critical: [1, 1]

this code for example will be aligned to the first line in the block. this means that the result in the yaml would be:

- name: logstash-forwarder
  search_string: ['logstash-forwarder']

notice that spacing. the - name is at the beginning of the line and search_string is two spaces behind.

This breaks the yaml format and should be handled.

**Comment by dobber** [comment]
http://pastie.org/10450801
with correct spaces

**Comment by yaegashi** [comment]
You might want to use [Block Indentation Indicator](http://www.yaml.org/spec/1.2/spec.html#id2793979) in YAML.

```yaml
- name: Add logstash-forwarder to datadog process monitoring
  blockinfile:
    dest: /etc/dd-agent/conf.d/process.yaml
    block: |2
        - name: logstash-forwarder
          search_string: ['logstash-forwarder']
        ...
```

Notice that the block content has indentation with 4 spaces.  You can get 2 space indented block from this task.

**Comment by kbroughton** [comment]
@yaegashi that is exactly what I want, but ansible 2.0.2 complains about the 

```
block: |2
```

It's fine if I remove the number 2.

**Comment by cfoutstd** [comment]
Still broken in ansible 2.1.1.0, that is the number in the block: | causes a syntax error.

**Comment by vmichnowicz** [comment]
It really does seem like the Block Indentation Indicator should work. I was not having any luck with it either unfortunately. It worked with one space, but anything else threw an error. I have resorted to putting the YAML all on one line:

``` yaml
- name: Add logstash-forwarder to datadog process monitoring
  blockinfile:
    dest: /etc/dd-agent/conf.d/process.yaml
    block: "  - name: logstash-forwarder\n    search_string: ['logstash-forwarder']"
```
