### ISSUE TITLE
Module doesn't work with PARAMETER= 

### ISSUE THREAD

**Issue by pgdagenais** [yaegashi/ansible-role-blockinfile#9]
``` yaml
- name: Add server as client
  blockinfile:
    dest: /etc/munin/munin.conf
    state: present
    marker: "#{mark} ANSIBLE MANAGED BLOCK"
    block: |
      [{{ ansible_hostname }}]
          address {{ ansible_eth1.ipv4.address }}
          use_node_name yes
```

This code work.

but when I try to use = instead of : it doesn't work anymore.

``` yaml
- name: Add server as client
  blockinfile: >
    dest=/etc/munin/munin.conf
    state=present
    marker="#{mark} ANSIBLE MANAGED BLOCK"
    block= |
      "[{{ ansible_hostname }}]
        address {{ ansible_eth1.ipv4.address }}
        use_node_name yes"
```

I get this error : 
`msg: this module requires key=value arguments (['dest=/etc/munin/munin.conf', 'state=present', 'marker=#{mark} ANSIBLE MANAGED BLOCK', 'block=', '|', '[monitoring-server]\naddress 192.168.35.17\nuse_node_name yes'])
`
